services:
  # 前端静态网站
  - type: web
    name: smart-community-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://smart-community-backend.onrender.com/api
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      # 缓存静态资源
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # 不缓存HTML文件
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    # SPA路由重定向 - 所有路径都指向index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 