services:
  # 后端API服务
  - type: web
    name: smart-community-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://smart-community-frontend.onrender.com
    healthCheckPath: /api/health 